name       : python-daemonize
version    : 2.4.7
release    : 1
source     :
    - https://pypi.python.org/packages/84/15/923e3fe48239adf5d697c29e04a3f868d3e4ce8539aab29d6abe784db5be/daemonize-2.4.7.tar.gz : c0194e861826be456c7c69985825ac7b79632d8ac7ad4cde8e12fee7971468c8
license    : MIT
component  : programming.python
summary    : Pythonic library to run your code as a daemon process
description: |
    Library to enable your code run as a daemon process on Unix-like systems.
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
install    : |
    %python3_install
